#!/bin/bash

if [ -f sparcs09/settings.real.py ]; then
    mv sparcs09/settings.py sparcs09/settings.test.py
    mv sparcs09/settings.real.py sparcs09/settings.py
    echo 'Changed to DEPLOY mode!'
else
    mv sparcs09/settings.py sparcs09/settings.real.py
    mv sparcs09/settings.test.py sparcs09/settings.py
    echo 'Changed to DEVELOP mode!'
fi
