# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/content'),
        ),
        migrations.AlterField(
            model_name='item',
            name='join_type',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Joined'), (2, 'Paid'), (3, 'Confirmed')]),
        ),
    ]
