# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170731_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='group',
            field=models.CharField(choices=[('sparcs09.account', 'sparcs09.account'), ('sparcs09.comment', 'sparcs09.comment'), ('sparcs09.item', 'sparcs09.item')], max_length=100),
        ),
    ]
