# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170731_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='item',
        ),
        migrations.RemoveField(
            model_name='record',
            name='participant',
        ),
        migrations.AddField(
            model_name='optioncategory',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='record',
            name='payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Payment'),
            preserve_default=False,
        ),
    ]
