# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170815_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='group',
            field=models.CharField(choices=[('sparcs09.account', 'sparcs09.account'), ('sparcs09.comment', 'sparcs09.comment'), ('sparcs09.item', 'sparcs09.item'), ('sparcs09.payment', 'sparcs09.payment')], max_length=100),
        ),
    ]
