# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170816_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
