# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170823_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
