# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20170625_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
