# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('group', models.CharField(choices=[('sparcs09.account', 'sparcs09.account')], max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('is_hidden', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
